# Generated by Django 4.0.1 on 2022-01-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_hosted',
            field=models.CharField(default='', max_length=300),
        ),
    ]
